"""Generates lib/core/locale/country_data.dart from CLDR (Babel) and
libphonenumber (phonenumbers). Re-run to refresh the data:

    pip install babel phonenumbers
    python tool/gen_countries.py
"""
import datetime
import os

from babel import Locale, localedata
from babel.numbers import get_currency_name, get_currency_symbol, get_territory_currencies
import phonenumbers

OUT = os.path.join(os.path.dirname(__file__), '..', 'lib', 'core', 'locale', 'country_data.dart')

en = Locale('en')
locale_ids = localedata.locale_identifiers()


def local_symbol(currency, territory):
    """The symbol the currency uses at home, e.g. ZAR -> R in en_ZA."""
    candidates = [f'en_{territory}'] + [l for l in locale_ids if l.endswith('_' + territory)]
    for lid in candidates:
        if lid not in locale_ids:
            continue
        sym = get_currency_symbol(currency, locale=lid)
        if sym and sym != currency:
            return sym
    return get_currency_symbol(currency, locale='en')


def q(s):
    # Dart single-quoted strings: escape backslash, quote and $ (interpolation).
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


rows = []
today = datetime.date.today()
for region in sorted(phonenumbers.SUPPORTED_REGIONS):
    name = en.territories.get(region)
    if not name:
        continue
    currencies = get_territory_currencies(region, start_date=today, end_date=today, tender=True)
    if not currencies:
        continue
    cur = currencies[0]
    dial = phonenumbers.country_code_for_region(region)
    rows.append((region, name, dial, cur, local_symbol(cur, region), get_currency_name(cur, locale='en')))

out = ["// GENERATED by tool/gen_countries.py from CLDR (Babel) and libphonenumber.",
       "// Do not edit by hand; regenerate instead.",
       "",
       "part of 'countries.dart';",
       "",
       "const List<Country> _countries = ["]
for iso, name, dial, cur, sym, cur_name in rows:
    out.append(f"  Country({q(iso)}, {q(name)}, {q(str(dial))}, {q(cur)}, {q(sym)}, {q(cur_name)}),")
out.append("];")
with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out) + '\n')
print(len(rows), 'countries written')
